/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/documents": {
    /** List Documents */
    get: operations["list_documents_v1_documents_get"];
    /** Upload Document */
    post: operations["upload_document_v1_documents_post"];
  };
  "/v1/documents/{document_id}/archive": {
    /** Archive Document */
    post: operations["archive_document_v1_documents__document_id__archive_post"];
  };
  "/v1/documents/{document_id}/unarchive": {
    /** Unarchive Document */
    post: operations["unarchive_document_v1_documents__document_id__unarchive_post"];
  };
  "/v1/documents/{document_id}": {
    /** Delete Document */
    delete: operations["delete_document_v1_documents__document_id__delete"];
  };
  "/v1/documents/{document_id}/reindex": {
    /** Reindex Document */
    post: operations["reindex_document_v1_documents__document_id__reindex_post"];
  };
  "/v1/documents/{document_id}/process": {
    /** Process Document */
    post: operations["process_document_v1_documents__document_id__process_post"];
  };
  "/v1/documents/{document_id}/file": {
    /** Download Document File */
    get: operations["download_document_file_v1_documents__document_id__file_get"];
  };
  "/v1/auth/login": {
    /** Login */
    post: operations["login_v1_auth_login_post"];
  };
  "/v1/auth/refresh": {
    /** Refresh */
    post: operations["refresh_v1_auth_refresh_post"];
  };
  "/v1/auth/logout": {
    /** Logout */
    post: operations["logout_v1_auth_logout_post"];
  };
  "/v1/auth/me": {
    /** Me */
    get: operations["me_v1_auth_me_get"];
  };
  "/v1/auth/me/change_password": {
    /** Change Password */
    post: operations["change_password_v1_auth_me_change_password_post"];
  };
  "/v1/auth/me/avatar": {
    /** Get My Avatar */
    get: operations["get_my_avatar_v1_auth_me_avatar_get"];
    /** Upload Avatar */
    post: operations["upload_avatar_v1_auth_me_avatar_post"];
  };
  "/v1/organizations": {
    /** List My Organizations */
    get: operations["list_my_organizations_v1_organizations_get"];
    /** Create Organization */
    post: operations["create_organization_v1_organizations_post"];
  };
  "/v1/organizations/{organization_id}": {
    /** Get Organization */
    get: operations["get_organization_v1_organizations__organization_id__get"];
    /** Delete Organization */
    delete: operations["delete_organization_v1_organizations__organization_id__delete"];
    /** Update Organization */
    patch: operations["update_organization_v1_organizations__organization_id__patch"];
  };
  "/v1/organizations/{organization_id}/suspend": {
    /** Suspend Organization */
    post: operations["suspend_organization_v1_organizations__organization_id__suspend_post"];
  };
  "/v1/organizations/{organization_id}/activate": {
    /** Activate Organization */
    post: operations["activate_organization_v1_organizations__organization_id__activate_post"];
  };
  "/v1/organizations/{organization_id}/members": {
    /** List Members */
    get: operations["list_members_v1_organizations__organization_id__members_get"];
    /** Add Member */
    post: operations["add_member_v1_organizations__organization_id__members_post"];
  };
  "/v1/organizations/{organization_id}/members/{membership_id}": {
    /** Remove Member */
    delete: operations["remove_member_v1_organizations__organization_id__members__membership_id__delete"];
    /** Update Member */
    patch: operations["update_member_v1_organizations__organization_id__members__membership_id__patch"];
  };
  "/v1/organizations/{organization_id}/members/{membership_id}/suspend": {
    /** Suspend Member */
    post: operations["suspend_member_v1_organizations__organization_id__members__membership_id__suspend_post"];
  };
  "/v1/organizations/{organization_id}/members/{membership_id}/activate": {
    /** Activate Member */
    post: operations["activate_member_v1_organizations__organization_id__members__membership_id__activate_post"];
  };
  "/v1/organizations/{organization_id}/transfer_ownership": {
    /** Transfer Ownership */
    post: operations["transfer_ownership_v1_organizations__organization_id__transfer_ownership_post"];
  };
  "/v1/invitations": {
    /** List Invitations */
    get: operations["list_invitations_v1_invitations_get"];
    /** Create Invitation */
    post: operations["create_invitation_v1_invitations_post"];
  };
  "/v1/invitations/accept": {
    /** Accept Invitation */
    post: operations["accept_invitation_v1_invitations_accept_post"];
  };
  "/v1/invitations/accept_logged_in": {
    /** Accept Invitation Logged In */
    post: operations["accept_invitation_logged_in_v1_invitations_accept_logged_in_post"];
  };
  "/v1/invitations/{invitation_id}/revoke": {
    /** Revoke Invitation */
    post: operations["revoke_invitation_v1_invitations__invitation_id__revoke_post"];
  };
  "/v1/invitations/{invitation_id}/resend": {
    /** Resend Invitation */
    post: operations["resend_invitation_v1_invitations__invitation_id__resend_post"];
  };
  "/v1/search": {
    /** Search Documents */
    get: operations["search_documents_v1_search_get"];
  };
  "/v1/search/mine": {
    /**
     * Search My Documents Across Orgs
     * @description Recherche "mes documents" sur toutes mes organisations.
     *
     * Règle: on retourne uniquement les documents uploadés par l'utilisateur, toutes orgs confondues
     * auxquelles il est membre (membership active).
     */
    get: operations["search_my_documents_across_orgs_v1_search_mine_get"];
  };
  "/v1/users/username_available": {
    /**
     * Username Available
     * @description Check if a username can be claimed by current user.
     */
    get: operations["username_available_v1_users_username_available_get"];
  };
  "/v1/users/directory": {
    /**
     * Directory
     * @description Typeahead directory scoped to current organization.
     *
     * Returns active org members only (enterprise-safe).
     */
    get: operations["directory_v1_users_directory_get"];
  };
  "/v1/users/me": {
    /** Update Me */
    patch: operations["update_me_v1_users_me_patch"];
  };
  "/v1/qa": {
    /** Answer Question */
    post: operations["answer_question_v1_qa_post"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AcceptInvitationLoggedInRequest */
    AcceptInvitationLoggedInRequest: {
      /** Token */
      token: string;
    };
    /** AcceptInvitationRequest */
    AcceptInvitationRequest: {
      /** Token */
      token: string;
      /** Display Name */
      display_name?: string | null;
      /** Password */
      password: string;
    };
    /** AddMemberRequest */
    AddMemberRequest: {
      /** User Email */
      user_email?: string | null;
      /** User Id */
      user_id?: string | null;
      /** Username */
      username?: string | null;
      /**
       * Role
       * @default member
       */
      role?: string;
    };
    /** Body_upload_avatar_v1_auth_me_avatar_post */
    Body_upload_avatar_v1_auth_me_avatar_post: {
      /** File */
      file: string;
    };
    /** Body_upload_document_v1_documents_post */
    Body_upload_document_v1_documents_post: {
      /** File */
      file: string;
    };
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /** CreateInvitationRequest */
    CreateInvitationRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /**
       * Role
       * @default member
       */
      role?: string;
    };
    /** CreateInvitationResponse */
    CreateInvitationResponse: {
      invitation: components["schemas"]["InvitationOut"];
      /** Token */
      token: string;
      /** Accept Url */
      accept_url: string;
    };
    /** CreateOrganizationRequest */
    CreateOrganizationRequest: {
      /** Name */
      name: string;
    };
    /** DocumentOut */
    DocumentOut: {
      /** Id */
      id: string;
      /** Organization Id */
      organization_id?: string | null;
      /** Filename */
      filename: string;
      /** Status */
      status: string;
      /** Storage Key */
      storage_key: string;
      /** Failed Reason */
      failed_reason?: string | null;
      /** Text Preview */
      text_preview?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InvitationOut */
    InvitationOut: {
      /** Id */
      id: string;
      /** Organization Id */
      organization_id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Role */
      role: string;
      /** Status */
      status: string;
      /** Expires At */
      expires_at: string;
      /** Accepted At */
      accepted_at?: string | null;
      /** Revoked At */
      revoked_at?: string | null;
      /** Created By User Id */
      created_by_user_id?: string | null;
      /** Created At */
      created_at?: string | null;
    };
    /** LoginRequest */
    LoginRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** MembershipOut */
    MembershipOut: {
      /** Id */
      id: string;
      /** User Id */
      user_id: string;
      /** Organization Id */
      organization_id: string;
      /** Role */
      role: string;
      /** Status */
      status: string;
    };
    /** OrganizationOut */
    OrganizationOut: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Status */
      status: string;
    };
    /** ProcessDocumentResponse */
    ProcessDocumentResponse: {
      document: components["schemas"]["DocumentOut"];
    };
    /** QARequest */
    QARequest: {
      /** Question */
      question: string;
      /**
       * Mode
       * @default org
       */
      mode?: string | null;
    };
    /** QAResponse */
    QAResponse: {
      /** Question */
      question: string;
      /** Answer */
      answer: string;
      /**
       * Abstained
       * @default false
       */
      abstained?: boolean;
      /** Sources */
      sources: components["schemas"]["QASource"][];
    };
    /** QASource */
    QASource: {
      /** Document Id */
      document_id: string;
      /** Filename */
      filename: string;
      /** Chunk Index */
      chunk_index: number;
      /** Score */
      score: number;
      /** Excerpt */
      excerpt: string;
    };
    /** RefreshRequest */
    RefreshRequest: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** SearchResponse */
    SearchResponse: {
      /** Query */
      query: string;
      /** Results */
      results: components["schemas"]["SearchResultItem"][];
    };
    /** SearchResultItem */
    SearchResultItem: {
      /** Document Id */
      document_id: string;
      /** Filename */
      filename: string;
      /** Score */
      score: number;
      /** Preview */
      preview?: string | null;
    };
    /** TokenPairResponse */
    TokenPairResponse: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type?: string;
      /** Expires In */
      expires_in: number;
    };
    /** TransferOwnershipRequest */
    TransferOwnershipRequest: {
      /** New Owner User Id */
      new_owner_user_id: string;
    };
    /** UpdateMemberRequest */
    UpdateMemberRequest: {
      /** Role */
      role?: string | null;
      /** Status */
      status?: string | null;
    };
    /** UpdateOrganizationRequest */
    UpdateOrganizationRequest: {
      /** Name */
      name?: string | null;
    };
    /** UpdateUserRequest */
    UpdateUserRequest: {
      /** Email */
      email?: string | null;
      /** Username */
      username?: string | null;
      /** Display Name */
      display_name?: string | null;
    };
    /** UploadDocumentResponse */
    UploadDocumentResponse: {
      document: components["schemas"]["DocumentOut"];
    };
    /** UserOut */
    UserOut: {
      /** Id */
      id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Username */
      username?: string | null;
      /** Display Name */
      display_name?: string | null;
      /** Avatar Storage Key */
      avatar_storage_key?: string | null;
      /** Status */
      status: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** List Documents */
  list_documents_v1_documents_get: {
    parameters: {
      query?: {
        include_archived?: boolean;
        q?: string | null;
        status?: ("uploaded" | "processing" | "processed" | "indexed" | "archived" | "failed" | "indexing_failed" | "indexing_pending") | null;
        sort?: "created_desc" | "updated_desc" | "name_asc";
        limit?: number;
      };
      header?: {
        "X-Org-Id"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DocumentOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Upload Document */
  upload_document_v1_documents_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_document_v1_documents_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UploadDocumentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Archive Document */
  archive_document_v1_documents__document_id__archive_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        document_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DocumentOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Unarchive Document */
  unarchive_document_v1_documents__document_id__unarchive_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        document_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DocumentOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Document */
  delete_document_v1_documents__document_id__delete: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        document_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reindex Document */
  reindex_document_v1_documents__document_id__reindex_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        document_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Process Document */
  process_document_v1_documents__document_id__process_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        document_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProcessDocumentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Download Document File */
  download_document_file_v1_documents__document_id__file_get: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        document_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login */
  login_v1_auth_login_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenPairResponse"];
        };
      };
      /** @description User disabled */
      403: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Refresh */
  refresh_v1_auth_refresh_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenPairResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Logout */
  logout_v1_auth_logout_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Me */
  me_v1_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /** Change Password */
  change_password_v1_auth_me_change_password_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get My Avatar */
  get_my_avatar_v1_auth_me_avatar_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Upload Avatar */
  upload_avatar_v1_auth_me_avatar_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_avatar_v1_auth_me_avatar_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List My Organizations */
  list_my_organizations_v1_organizations_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OrganizationOut"][];
        };
      };
    };
  };
  /** Create Organization */
  create_organization_v1_organizations_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrganizationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OrganizationOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Organization */
  get_organization_v1_organizations__organization_id__get: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        organization_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OrganizationOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Organization */
  delete_organization_v1_organizations__organization_id__delete: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        organization_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Organization */
  update_organization_v1_organizations__organization_id__patch: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        organization_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateOrganizationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OrganizationOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Suspend Organization */
  suspend_organization_v1_organizations__organization_id__suspend_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        organization_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OrganizationOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Activate Organization */
  activate_organization_v1_organizations__organization_id__activate_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        organization_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OrganizationOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Members */
  list_members_v1_organizations__organization_id__members_get: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        organization_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MembershipOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Add Member */
  add_member_v1_organizations__organization_id__members_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        organization_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddMemberRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MembershipOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Remove Member */
  remove_member_v1_organizations__organization_id__members__membership_id__delete: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        organization_id: string;
        membership_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Member */
  update_member_v1_organizations__organization_id__members__membership_id__patch: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        organization_id: string;
        membership_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMemberRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MembershipOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Suspend Member */
  suspend_member_v1_organizations__organization_id__members__membership_id__suspend_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        organization_id: string;
        membership_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MembershipOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Activate Member */
  activate_member_v1_organizations__organization_id__members__membership_id__activate_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        organization_id: string;
        membership_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MembershipOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Transfer Ownership */
  transfer_ownership_v1_organizations__organization_id__transfer_ownership_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        organization_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransferOwnershipRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Invitations */
  list_invitations_v1_invitations_get: {
    parameters: {
      query?: {
        status?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: {
        "X-Org-Id"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InvitationOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Invitation */
  create_invitation_v1_invitations_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateInvitationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CreateInvitationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Accept Invitation */
  accept_invitation_v1_invitations_accept_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcceptInvitationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Accept Invitation Logged In */
  accept_invitation_logged_in_v1_invitations_accept_logged_in_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcceptInvitationLoggedInRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Revoke Invitation */
  revoke_invitation_v1_invitations__invitation_id__revoke_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        invitation_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Resend Invitation */
  resend_invitation_v1_invitations__invitation_id__resend_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        invitation_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CreateInvitationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Search Documents */
  search_documents_v1_search_get: {
    parameters: {
      query: {
        q: string;
      };
      header?: {
        "X-Org-Id"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Search My Documents Across Orgs
   * @description Recherche "mes documents" sur toutes mes organisations.
   *
   * Règle: on retourne uniquement les documents uploadés par l'utilisateur, toutes orgs confondues
   * auxquelles il est membre (membership active).
   */
  search_my_documents_across_orgs_v1_search_mine_get: {
    parameters: {
      query: {
        q: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Username Available
   * @description Check if a username can be claimed by current user.
   */
  username_available_v1_users_username_available_get: {
    parameters: {
      query: {
        username: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Directory
   * @description Typeahead directory scoped to current organization.
   *
   * Returns active org members only (enterprise-safe).
   */
  directory_v1_users_directory_get: {
    parameters: {
      query?: {
        q?: string | null;
        limit?: number;
      };
      header?: {
        "X-Org-Id"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Me */
  update_me_v1_users_me_patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Answer Question */
  answer_question_v1_qa_post: {
    parameters: {
      header?: {
        "X-Org-Id"?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["QARequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["QAResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
